DROP TABLE IF EXISTS sys_global_config;
CREATE TABLE `sys_global_config` (
  `config_code` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '配置CODE值',
  `group_flag` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '分组标识',
  `json_value` JSON NOT NULL COMMENT '配置值',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '已删除：0否，1是',
  PRIMARY KEY (`config_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='系统全局配置';